### ISSUE TITLE
very weird and unintuitive ctrl-v paste

### ISSUE THREAD

**Issue by JinnCirce** [SebastianMuskalla/ModelessVim#1]
paste should use <kbd>P</kbd> not <kbd>p</kbd>, very weird and unintuitive <kbd>ctrl-v</kbd> the way it is now
trivial fix, like
```vimrc
noremap! <C-V> <C-O>gP
```

other than that, pretty cool project!

**Comment by octoshrimpy** [comment]
ctrl-P is often used for opening print dialogs. V was chosen was it i close to C, allowing single-hand macro operation in standard QWERTY/QWERTZ keyboards. ctrl-V is the  industry standard across many many apps and OSes, as well as ctrl-P for printing.

**Comment by JinnCirce** [comment]
> ctrl-P is often used for opening print dialogs. V was chosen was it i close to C, allowing single-hand macro operation in standard QWERTY/QWERTZ keyboards. ctrl-V is the  industry standard across many many apps and OSes, as well as ctrl-P for printing. 

you're not understanding...
obviously keep ctrl-V on the user side...
the problem is that pasting with THIS config, does NOT work the same as in EVERY OTHER APP OUT THERE, which is caused by using lowercase p, instead of uppercase P, on vim's side config...
in EVERY app out there, pasting stuff pastes AFTER the cursor...

**Comment by SebastianMuskalla** [comment]
Hey! Thanks for opening this issue.
I didn't realize that there are issues with copying/pasting as I am using Windows Terminal, which overrides Ctrl+C/V.

Unfortunately, even in another terminal emulator, I struggle to reproduce the issue.

> in EVERY app out there, pasting stuff pastes AFTER the cursor...

This should be exactly what `gp` does:
From `:help p`:

```
["x]p                   Put the text [from register x] after the cursor
                        [count] times.
["x]P                   Put the text [from register x] before the cursor
                        [count] times.
```

In my tests, `Ctrl+V` seems to behave as it should:
It pastes the copied text after the cursor (`p` command) and then moves the cursor after the pasted text (`g` prefix).

Am I making a mistake?
Can you help me to reproduce the issue you are facing?
